apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-go-hpa
  labels:
    app: hello-go
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-go
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30